# Generated by Django 6.0.3 on 2026-03-18 02:23

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearcherPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('field', models.CharField(max_length=255)),
                ('content', wagtail.fields.StreamField([('section', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('researchers.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.URLBlock', (), {}), 3: ('wagtail.blocks.StructBlock', [[('text', 0), ('url', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'required': False}), 5: ('wagtail.blocks.IntegerBlock', (), {'required': False}), 6: ('wagtail.blocks.URLBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('authors', 4), ('year', 5), ('link', 6)]], {}), 8: ('researchers.blocks.GalleryBlock', (), {}), 9: ('wagtail.blocks.StreamBlock', [[('text', 1), ('link', 3), ('publication', 7), ('gallery', 8)]], {}), 10: ('wagtail.blocks.StructBlock', [[('heading', 0), ('content', 9)]], {})})),
                ('profile_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
