# Generated by Django 5.2.14 on 2026-05-13 08:44

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearcherSectionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('smart_content', wagtail.fields.StreamField([('publication', 4), ('guidance', 5), ('news', 7), ('supervision', 8), ('gallery', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.IntegerBlock', (), {'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('journal', 1), ('year', 2), ('link', 3)]], {}), 5: ('wagtail.blocks.StructBlock', [[('student_name', 0), ('thesis_title', 0), ('year', 2), ('link', 3)]], {}), 6: ('wagtail.blocks.DateBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('headline', 0), ('source', 1), ('date', 6), ('link', 3)]], {}), 8: ('wagtail.blocks.StructBlock', [[('student', 0), ('topic', 0), ('year', 2)]], {}), 9: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 10: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption for the image', 'required': False}), 11: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline'], 'help_text': 'Optional rich text shown in the gallery modal as About this Image', 'required': False}), 12: ('wagtail.blocks.StructBlock', [[('image', 9), ('caption', 10), ('about_image', 11)]], {}), 13: ('wagtail.blocks.ListBlock', (12,), {'label': 'Gallery Images'}), 14: ('wagtail.blocks.StructBlock', [[('title', 1), ('images', 13)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ResearcherPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('field', models.CharField(max_length=255)),
                ('profile_items', wagtail.fields.StreamField([('profile_item', 1)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.StructBlock', [[('label', 0), ('value', 0)]], {})}, help_text='Add rows like Born, Field, Institution. You can add, reorder, or remove items.')),
                ('sidebar_items', wagtail.fields.StreamField([('sidebar_item', 22)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Used for URL routing', 'required': True}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Author, source, or category', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Year, date, or additional info', 'required': False}), 6: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline', 'link', 'ol', 'ul', 'h2', 'h3', 'h4'], 'help_text': 'Brief description with formatting support', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('link', 3), ('tag', 4), ('meta_text', 5), ('description', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.IntegerBlock', (), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('title', 0), ('journal', 1), ('year', 9), ('link', 3)]], {}), 11: ('wagtail.blocks.StructBlock', [[('student_name', 0), ('thesis_title', 0), ('year', 9), ('link', 3)]], {}), 12: ('wagtail.blocks.DateBlock', (), {'required': False}), 13: ('wagtail.blocks.StructBlock', [[('headline', 0), ('source', 1), ('date', 12), ('link', 3)]], {}), 14: ('wagtail.blocks.StructBlock', [[('student', 0), ('topic', 0), ('year', 9)]], {}), 15: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 16: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption for the image', 'required': False}), 17: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline'], 'help_text': 'Optional rich text shown in the gallery modal as About this Image', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('image', 15), ('caption', 16), ('about_image', 17)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {'label': 'Gallery Images'}), 20: ('wagtail.blocks.StructBlock', [[('title', 1), ('images', 19)]], {}), 21: ('wagtail.blocks.StreamBlock', [[('publication', 10), ('guidance', 11), ('news', 13), ('supervision', 14), ('gallery', 20)]], {'required': False}), 22: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('slug', 2), ('items', 8), ('smart_content', 21)]], {})}, help_text='Add and reorder sidebar navigation items and their content.')),
                ('bio_sections', wagtail.fields.StreamField([('bio_section', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline', 'link', 'ol', 'ul', 'h2', 'h3', 'h4'], 'help_text': 'Rich text with bold, italic, underline, links, and lists', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('content', 1)]], {})}, help_text='Add and reorder biography sections for center content.')),
                ('profile_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
