# Generated by Django 6.0.3 on 2026-03-20 07:23

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0002_alter_researcherpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcherpage',
            name='content',
            field=wagtail.fields.StreamField([('bio', 0), ('publication', 4), ('gallery', 6), ('guidance', 8)], blank=True, block_lookup={0: ('wagtail.blocks.RichTextBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {}), 2: ('wagtail.blocks.IntegerBlock', (), {}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 1), ('year', 2), ('journal', 1), ('link', 3)]], {}), 5: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 6: ('wagtail.blocks.ListBlock', (5,), {}), 7: ('wagtail.blocks.TextBlock', (), {}), 8: ('wagtail.blocks.StructBlock', [[('title', 1), ('description', 7)]], {})}),
        ),
    ]
