# Generated by Django 6.0.3 on 2026-03-20 13:42

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0003_alter_researcherpage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcherpage',
            name='profile_details',
            field=wagtail.fields.StreamField([('profile_item', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.TextBlock', (), {}), 2: ('wagtail.blocks.StructBlock', [[('label', 0), ('content', 1)]], {})}),
        ),
    ]
