# Generated by Django 6.0.3 on 2026-03-20 14:05

import wagtail.fields
from django.db import migrations


def forward_profile_items_data(apps, schema_editor):
    ResearcherPage = apps.get_model('researchers', 'ResearcherPage')

    for page in ResearcherPage.objects.all():
        stream_value = page.profile_items
        raw_blocks = getattr(stream_value, 'stream_data', stream_value) or []
        updated_blocks = []

        for block in raw_blocks:
            if not isinstance(block, dict):
                continue

            block_value = block.get('value') or {}
            label = block_value.get('label')
            value = block_value.get('value')

            if value in (None, ''):
                value = block_value.get('content', '')

            updated_blocks.append(
                {
                    **block,
                    'value': {
                        'label': label,
                        'value': value,
                    },
                }
            )

        page.profile_items = updated_blocks
        page.save(update_fields=['profile_items'])


def backward_profile_items_data(apps, schema_editor):
    ResearcherPage = apps.get_model('researchers', 'ResearcherPage')

    for page in ResearcherPage.objects.all():
        stream_value = page.profile_items
        raw_blocks = getattr(stream_value, 'stream_data', stream_value) or []
        updated_blocks = []

        for block in raw_blocks:
            if not isinstance(block, dict):
                continue

            block_value = block.get('value') or {}

            updated_blocks.append(
                {
                    **block,
                    'value': {
                        'label': block_value.get('label'),
                        'content': block_value.get('value', ''),
                    },
                }
            )

        page.profile_items = updated_blocks
        page.save(update_fields=['profile_items'])


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0004_researcherpage_profile_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='researcherpage',
            old_name='profile_details',
            new_name='profile_items',
        ),
        migrations.RunPython(
            forward_profile_items_data,
            backward_profile_items_data,
        ),
        migrations.AlterField(
            model_name='researcherpage',
            name='profile_items',
            field=wagtail.fields.StreamField([('profile_item', 1)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.StructBlock', [[('label', 0), ('value', 0)]], {})}),
        ),
    ]
