# Generated by Django 6.0.3 on 2026-03-20 14:12

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0005_remove_researcherpage_profile_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcherpage',
            name='profile_items',
            field=wagtail.fields.StreamField([('profile_item', 1)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.StructBlock', [[('label', 0), ('value', 0)]], {})}, help_text='Add rows like Born, Field, Institution. You can add, reorder, or remove items.'),
        ),
    ]
