# Generated by Django 6.0.3 on 2026-03-20 15:44

import re

import wagtail.fields
from django.db import migrations


def to_slug(value):
    slug = re.sub(r"[^a-z0-9\s-]", "", str(value or "").lower().strip())
    slug = re.sub(r"\s+", "-", slug)
    slug = re.sub(r"-+", "-", slug)
    return slug


def forward_convert_content_to_sections(apps, schema_editor):
    ResearcherPage = apps.get_model("researchers", "ResearcherPage")

    for page in ResearcherPage.objects.all():
        stream_value = page.content
        raw_blocks = getattr(stream_value, "stream_data", stream_value) or []

        if not isinstance(raw_blocks, list) or len(raw_blocks) == 0:
            continue

        if all((block or {}).get("type") == "section" for block in raw_blocks if isinstance(block, dict)):
            continue

        transformed_sections = []
        publication_items = []
        gallery_images = []

        for block in raw_blocks:
            if not isinstance(block, dict):
                continue

            block_type = block.get("type") or block.get("block_type")
            value = block.get("value") or {}

            if block_type == "bio":
                transformed_sections.append(
                    {
                        "type": "section",
                        "value": {
                            "title": "Bio",
                            "slug": "bio",
                            "content": value,
                            "images": [],
                            "items": [],
                        },
                    }
                )
                continue

            if block_type == "guidance":
                title = str(value.get("title") or "Guidance").strip()
                transformed_sections.append(
                    {
                        "type": "section",
                        "value": {
                            "title": title,
                            "slug": to_slug(title) or "guidance",
                            "content": value.get("description") or "",
                            "images": [],
                            "items": [],
                        },
                    }
                )
                continue

            if block_type == "publication":
                publication_title = str(value.get("title") or "Publication").strip()
                details = []

                if value.get("journal"):
                    details.append(f"Journal: {value.get('journal')}")
                if value.get("year"):
                    details.append(f"Year: {value.get('year')}")
                if value.get("link"):
                    details.append(f"Link: {value.get('link')}")

                publication_items.append(
                    {
                        "title": publication_title,
                        "description": "\n".join(details),
                    }
                )
                continue

            if block_type == "gallery":
                image_ids = value if isinstance(value, list) else []
                gallery_images.extend([image_id for image_id in image_ids if image_id])

        if publication_items:
            transformed_sections.append(
                {
                    "type": "section",
                    "value": {
                        "title": "Publications",
                        "slug": "publications",
                        "content": "",
                        "images": [],
                        "items": publication_items,
                    },
                }
            )

        if gallery_images:
            transformed_sections.append(
                {
                    "type": "section",
                    "value": {
                        "title": "Photo Gallery",
                        "slug": "photo-gallery",
                        "content": "",
                        "images": gallery_images,
                        "items": [],
                    },
                }
            )

        page.content = transformed_sections
        page.save(update_fields=["content"])


def backward_convert_content_to_sections(apps, schema_editor):
    return


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0007_sitesettings'),
    ]

    operations = [
        migrations.RunPython(
            forward_convert_content_to_sections,
            backward_convert_content_to_sections,
        ),
        migrations.AlterField(
            model_name='researcherpage',
            name='content',
            field=wagtail.fields.StreamField([('section', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Used for URL and sidebar', 'required': True}), 2: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 3: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 4: ('wagtail.blocks.ListBlock', (3,), {'required': False}), 5: ('wagtail.blocks.CharBlock', (), {}), 6: ('wagtail.blocks.TextBlock', (), {}), 7: ('wagtail.blocks.StructBlock', [[('title', 5), ('description', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {'required': False}), 9: ('wagtail.blocks.StructBlock', [[('title', 0), ('slug', 1), ('content', 2), ('images', 4), ('items', 8)]], {})}),
        ),
    ]
