# Generated by Django 6.0.3 on 2026-03-20 16:12

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0008_alter_researcherpage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcherpage',
            name='content',
            field=wagtail.fields.StreamField([('section', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Used for URL and sidebar', 'required': True}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', 'Text Section'), ('gallery', 'Gallery Section'), ('list', 'List Section')], 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.ListBlock', (4,), {'required': False}), 6: ('wagtail.blocks.CharBlock', (), {}), 7: ('wagtail.blocks.TextBlock', (), {}), 8: ('wagtail.blocks.StructBlock', [[('title', 6), ('description', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('title', 0), ('slug', 1), ('type', 2), ('content', 3), ('images', 5), ('items', 9)]], {})}),
        ),
    ]
