# Generated by Django 6.0.3 on 2026-03-21 06:30

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0009_alter_researcherpage_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='researcherpage',
            name='bio_sections',
            field=wagtail.fields.StreamField([('bio_section', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('content', 1)]], {})}, help_text='Add and reorder biography sections for center content.'),
        ),
        migrations.AddField(
            model_name='researcherpage',
            name='sidebar_items',
            field=wagtail.fields.StreamField([('sidebar_item', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Used for URL routing', 'required': True}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.RichTextBlock', (), {'required': True}), 5: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('slug', 2), ('external_url', 3), ('content', 4)]], {})}, help_text='Add and reorder sidebar navigation items and their content.'),
        ),
    ]
