# Generated by Django 6.0.3 on 2026-03-21 06:54

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0010_researcherpage_bio_sections_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcherpage',
            name='sidebar_items',
            field=wagtail.fields.StreamField([('sidebar_item', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Used for URL routing', 'required': True}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Author, source, or category', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Year, date, or additional info', 'required': False}), 6: ('wagtail.blocks.TextBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('link', 3), ('tag', 4), ('meta_text', 5), ('description', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('slug', 2), ('items', 8)]], {})}, help_text='Add and reorder sidebar navigation items and their content.'),
        ),
    ]
