# Generated by Django 6.0.3 on 2026-03-21 14:00

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0011_alter_researcherpage_sidebar_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcherpage',
            name='bio_sections',
            field=wagtail.fields.StreamField([('bio_section', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline', 'link', 'ol', 'ul', 'h2', 'h3', 'h4'], 'help_text': 'Rich text with bold, italic, underline, links, and lists', 'required': True}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('content', 1)]], {})}, help_text='Add and reorder biography sections for center content.'),
        ),
        migrations.AlterField(
            model_name='researcherpage',
            name='content',
            field=wagtail.fields.StreamField([('section', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Used for URL and sidebar', 'required': True}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', 'Text Section'), ('gallery', 'Gallery Section'), ('list', 'List Section')], 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline', 'link', 'ol', 'ul', 'h2', 'h3', 'h4'], 'help_text': 'Rich text with bold, italic, underline, links, and lists', 'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 5: ('wagtail.blocks.ListBlock', (4,), {'required': False}), 6: ('wagtail.blocks.CharBlock', (), {}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline', 'link', 'ol', 'ul', 'h2', 'h3', 'h4'], 'help_text': 'Rich text with formatting support', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('title', 6), ('description', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('title', 0), ('slug', 1), ('type', 2), ('content', 3), ('images', 5), ('items', 9)]], {})}),
        ),
        migrations.AlterField(
            model_name='researcherpage',
            name='sidebar_items',
            field=wagtail.fields.StreamField([('sidebar_item', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Used for URL routing', 'required': True}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Author, source, or category', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Year, date, or additional info', 'required': False}), 6: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'help_text': 'Brief description with basic formatting', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('link', 3), ('tag', 4), ('meta_text', 5), ('description', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('slug', 2), ('items', 8)]], {})}, help_text='Add and reorder sidebar navigation items and their content.'),
        ),
    ]
