# Generated by Django 6.0.3 on 2026-03-23 09:59

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0013_researcherpage_smart_content_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearcherSectionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('smart_content', wagtail.fields.StreamField([('publication', 4), ('guidance', 5), ('news', 7), ('supervision', 8)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.IntegerBlock', (), {'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('journal', 1), ('year', 2), ('link', 3)]], {}), 5: ('wagtail.blocks.StructBlock', [[('student_name', 0), ('thesis_title', 0), ('year', 2)]], {}), 6: ('wagtail.blocks.DateBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('headline', 0), ('source', 1), ('date', 6), ('link', 3)]], {}), 8: ('wagtail.blocks.StructBlock', [[('student', 0), ('topic', 0), ('year', 2)]], {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
