# Generated by Django 6.0.3 on 2026-03-24 10:27

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0014_researchersectionpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcherpage',
            name='sidebar_items',
            field=wagtail.fields.StreamField([('sidebar_item', 20)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Used for URL routing', 'required': True}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Author, source, or category', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Year, date, or additional info', 'required': False}), 6: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline', 'link', 'ol', 'ul', 'h2', 'h3', 'h4'], 'help_text': 'Brief description with formatting support', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('link', 3), ('tag', 4), ('meta_text', 5), ('description', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.IntegerBlock', (), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('title', 0), ('journal', 1), ('year', 9), ('link', 3)]], {}), 11: ('wagtail.blocks.StructBlock', [[('student_name', 0), ('thesis_title', 0), ('year', 9)]], {}), 12: ('wagtail.blocks.DateBlock', (), {'required': False}), 13: ('wagtail.blocks.StructBlock', [[('headline', 0), ('source', 1), ('date', 12), ('link', 3)]], {}), 14: ('wagtail.blocks.StructBlock', [[('student', 0), ('topic', 0), ('year', 9)]], {}), 15: ('wagtail.blocks.StreamBlock', [[('publication', 10), ('guidance', 11), ('news', 13), ('supervision', 14)]], {'required': False}), 16: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': True}), 17: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption for the image', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('image', 16), ('caption', 17)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {'help_text': 'Add images to create a gallery for this section', 'required': False}), 20: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('slug', 2), ('items', 8), ('smart_content', 15), ('gallery', 19)]], {})}, help_text='Add and reorder sidebar navigation items and their content.'),
        ),
    ]
