# Generated by Django 6.0.3 on 2026-03-26 16:01

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0017_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcherpage',
            name='content',
            field=wagtail.fields.StreamField([('section', 10)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Used for URL and sidebar', 'required': True}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', 'Text Section'), ('gallery', 'Gallery Section'), ('list', 'List Section')], 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline', 'link', 'ol', 'ul', 'h2', 'h3', 'h4'], 'help_text': 'Rich text with bold, italic, underline, links, and lists', 'required': False}), 4: ('researchers.blocks.RenditionImageChooserBlock', (), {}), 5: ('wagtail.blocks.ListBlock', (4,), {'required': False}), 6: ('wagtail.blocks.CharBlock', (), {}), 7: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline', 'link', 'ol', 'ul', 'h2', 'h3', 'h4'], 'help_text': 'Rich text with formatting support', 'required': False}), 8: ('wagtail.blocks.StructBlock', [[('title', 6), ('description', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('title', 0), ('slug', 1), ('type', 2), ('content', 3), ('images', 5), ('items', 9)]], {})}),
        ),
        migrations.AlterField(
            model_name='researcherpage',
            name='sidebar_items',
            field=wagtail.fields.StreamField([('sidebar_item', 23)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Used for URL routing', 'required': True}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.CharBlock', (), {'help_text': 'Author, source, or category', 'required': False}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'Year, date, or additional info', 'required': False}), 6: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline', 'link', 'ol', 'ul', 'h2', 'h3', 'h4'], 'help_text': 'Brief description with formatting support', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 0), ('link', 3), ('tag', 4), ('meta_text', 5), ('description', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.IntegerBlock', (), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('title', 0), ('journal', 1), ('year', 9), ('link', 3)]], {}), 11: ('wagtail.blocks.StructBlock', [[('student_name', 0), ('thesis_title', 0), ('year', 9)]], {}), 12: ('wagtail.blocks.DateBlock', (), {'required': False}), 13: ('wagtail.blocks.StructBlock', [[('headline', 0), ('source', 1), ('date', 12), ('link', 3)]], {}), 14: ('wagtail.blocks.StructBlock', [[('student', 0), ('topic', 0), ('year', 9)]], {}), 15: ('researchers.blocks.RenditionImageChooserBlock', (), {}), 16: ('wagtail.blocks.ListBlock', (15,), {'required': True}), 17: ('wagtail.blocks.StructBlock', [[('title', 1), ('images', 16)]], {}), 18: ('wagtail.blocks.StreamBlock', [[('publication', 10), ('guidance', 11), ('news', 13), ('supervision', 14), ('gallery', 17)]], {'required': False}), 19: ('researchers.blocks.RenditionImageChooserBlock', (), {'required': True}), 20: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional caption for the image', 'required': False}), 21: ('wagtail.blocks.StructBlock', [[('image', 19), ('caption', 20)]], {}), 22: ('wagtail.blocks.ListBlock', (21,), {'help_text': 'Add images to create a gallery for this section', 'required': False}), 23: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('slug', 2), ('items', 8), ('smart_content', 18), ('gallery', 22)]], {})}, help_text='Add and reorder sidebar navigation items and their content.'),
        ),
        migrations.AlterField(
            model_name='researcherpage',
            name='smart_content',
            field=wagtail.fields.StreamField([('publication', 4), ('guidance', 5), ('news', 7), ('supervision', 8), ('gallery', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.IntegerBlock', (), {'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('journal', 1), ('year', 2), ('link', 3)]], {}), 5: ('wagtail.blocks.StructBlock', [[('student_name', 0), ('thesis_title', 0), ('year', 2)]], {}), 6: ('wagtail.blocks.DateBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('headline', 0), ('source', 1), ('date', 6), ('link', 3)]], {}), 8: ('wagtail.blocks.StructBlock', [[('student', 0), ('topic', 0), ('year', 2)]], {}), 9: ('researchers.blocks.RenditionImageChooserBlock', (), {}), 10: ('wagtail.blocks.ListBlock', (9,), {'required': True}), 11: ('wagtail.blocks.StructBlock', [[('title', 1), ('images', 10)]], {})}),
        ),
        migrations.AlterField(
            model_name='researchersectionpage',
            name='smart_content',
            field=wagtail.fields.StreamField([('publication', 4), ('guidance', 5), ('news', 7), ('supervision', 8), ('gallery', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'required': False}), 2: ('wagtail.blocks.IntegerBlock', (), {'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('journal', 1), ('year', 2), ('link', 3)]], {}), 5: ('wagtail.blocks.StructBlock', [[('student_name', 0), ('thesis_title', 0), ('year', 2)]], {}), 6: ('wagtail.blocks.DateBlock', (), {'required': False}), 7: ('wagtail.blocks.StructBlock', [[('headline', 0), ('source', 1), ('date', 6), ('link', 3)]], {}), 8: ('wagtail.blocks.StructBlock', [[('student', 0), ('topic', 0), ('year', 2)]], {}), 9: ('researchers.blocks.RenditionImageChooserBlock', (), {}), 10: ('wagtail.blocks.ListBlock', (9,), {'required': True}), 11: ('wagtail.blocks.StructBlock', [[('title', 1), ('images', 10)]], {})}),
        ),
    ]
