# Generated by Django 6.0.3 on 2026-03-26 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0019_alter_researcherpage_content_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
