# Generated by Django 6.0.3 on 2026-03-26 18:20

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0021_alter_researcherpage_sidebar_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='researcherpage',
            name='content',
            field=wagtail.fields.StreamField([('section', 8), ('gallery', 12)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Used for URL and sidebar', 'required': True}), 2: ('wagtail.blocks.ChoiceBlock', [], {'choices': [('text', 'Text Section'), ('list', 'List Section')], 'required': False}), 3: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline', 'link', 'ol', 'ul', 'h2', 'h3', 'h4'], 'help_text': 'Rich text with bold, italic, underline, links, and lists', 'required': False}), 4: ('wagtail.blocks.CharBlock', (), {}), 5: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'underline', 'link', 'ol', 'ul', 'h2', 'h3', 'h4'], 'help_text': 'Rich text with formatting support', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('title', 4), ('description', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {'required': False}), 8: ('wagtail.blocks.StructBlock', [[('title', 0), ('slug', 1), ('type', 2), ('content', 3), ('items', 7)]], {}), 9: ('wagtail.blocks.CharBlock', (), {'required': False}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {}), 11: ('wagtail.blocks.ListBlock', (10,), {'label': 'Gallery Images'}), 12: ('wagtail.blocks.StructBlock', [[('title', 9), ('images', 11)]], {})}),
        ),
    ]
