# Generated by Django 6.0.3 on 2026-04-18 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researchers', '0024_alter_researcherpage_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='researcherpage',
            name='content',
        ),
        migrations.RemoveField(
            model_name='researcherpage',
            name='smart_content',
        ),
    ]
